project_id = "wjyyfqxblicvrbaycoaq"

[functions.notify-artists]
verify_jwt = true

[functions.send-booking-notification]
verify_jwt = true

[functions.send-password-reset]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = true

[functions.log-error]
verify_jwt = false

[functions.generate-artist-bio]
verify_jwt = false

[functions.send-dispute-notification]
verify_jwt = false

[functions.create-connect-account]
verify_jwt = false

[functions.check-connect-status]
verify_jwt = false

[functions.create-booking-payment]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-connect-dashboard]
verify_jwt = false
