// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-artists.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.93.3";
import { z } from "npm:zod@^3.23.8";
var search_artists_default = defineTool({
  name: "search_artists",
  title: "Search artists",
  description: "Search approved artists on OnTour by city and/or genre. Returns basic public profile info (name, city, genres, rating, bio).",
  inputSchema: {
    city: z.string().optional().describe("Filter by artist primary city (case-insensitive partial match)."),
    genre: z.string().optional().describe("Filter by a single genre slug (e.g. 'house', 'hip_hop')."),
    limit: z.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ city, genre, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    let q = supabase.from("artists").select("id, artist_name, primary_city, genres, bio, average_rating, total_reviews, profile_image_url").eq("review_status", "approved").limit(limit);
    if (city) q = q.ilike("primary_city", `%${city}%`);
    if (genre) q = q.contains("genres", [genre]);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { artists: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-artist.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.93.3";
import { z as z2 } from "npm:zod@^3.23.8";
var get_artist_default = defineTool2({
  name: "get_artist",
  title: "Get artist",
  description: "Fetch a single approved artist's public profile by artist id.",
  inputSchema: {
    id: z2.string().uuid().describe("Artist id (uuid).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    const { data, error } = await supabase.from("artists").select(
      "id, artist_name, primary_city, genres, bio, average_rating, total_reviews, profile_image_url, spotify_url, soundcloud_url, instagram_url, tiktok_url"
    ).eq("id", id).eq("review_status", "approved").maybeSingle();
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Artist not found." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { artist: data }
    };
  }
});

// src/lib/mcp/tools/search-venues.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.93.3";
import { z as z3 } from "npm:zod@^3.23.8";
var search_venues_default = defineTool3({
  name: "search_venues",
  title: "Search venues",
  description: "Search approved venues on OnTour by city. Returns basic public profile info.",
  inputSchema: {
    city: z3.string().optional().describe("Filter by venue city (case-insensitive partial match)."),
    limit: z3.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ city, limit }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    let q = supabase.from("venues").select("*").limit(limit);
    if (city) q = q.ilike("city", `%${city}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { venues: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "ontour-mcp",
  title: "OnTour",
  version: "0.1.0",
  instructions: "Tools for OnTour, a marketplace connecting venues with DJs and live artists. Use search_artists / get_artist to discover talent and search_venues to explore venues. All data returned is public profile information for approved users.",
  tools: [search_artists_default, get_artist_default, search_venues_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
